services:
  server:
    container_name: skribbl_server
    build: . 
    ports:
      - '4000:4000'
    environment:
      MONGO_URI: mongodb://db:27017/?directConnection=true
      REDIS_URI: redis://redis:6379
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json

  db: 
    container_name: skribbl_db
    image: mongo 
    ports:
      - '27018:27017'
    volumes:
      - db_data:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all"]

  mongo-init:
    container_name: mongo_rs
    image: mongo
    restart: "no"
    depends_on:
      - db
    command: >
      sh -c "sleep 5; mongosh \"mongodb://db:27017\" --eval '
      rs.initiate()
      '"

  redis:
    container_name: skribbl_redis
    image: redis

volumes:
  db_data:
    external: true
    name: skribbl_db_data
    

