services:
  server:
    container_name: skribbl_server
    build: . 
    ports:
      - '4000:4000'
    environment:
      - MONGO_URI=mongodb://db:27017/

  db: 
    container_name: skribbl_db
    image: mongo 
    ports:
      - '27018:27017'
    volumes:
      - db_data:/data/db

volumes:
  db_data:

