services:
  skribbl-server:
    build: .
    container_name: skribbl-server
    ports:
      - '4000:4000'
    links:
      - mongo
    volumes:
      - /app/src
      - ./src:/app/src

  mongo: 
    container_name: mongo
    image: mongo
    ports:
      - '27018:27017'